import {
  sanitizeLang,
  muxGetAsset,
  pickTextTrackByLang,
  fetchVttFromMux,
} from '../helpers/videoModeration.shared.js';
import { readPool } from '../../../database/index.js';
import { HttpError } from '../../../common/httpError.js';

export async function autogenerateDetailsInternal({ params: routeParams, query: queryParams }) {
  const { videoId } = routeParams;
  const type = sanitizeLang(queryParams.type);

  if (!type) {
    throw new HttpError(400, {
      message: 'Missing query param: type (e.g. ?type=title/description/tags)',
    });
  }

  try {
    // 1) DB: uzmi mux ids
    const { rows } = await readPool.query(
      `SELECT mux_asset_id, mux_playback_id FROM public.videos WHERE id = $1 LIMIT 1`,
      [videoId],
    );
    const assetId = rows[0]?.mux_asset_id;
    const playbackId = rows[0]?.mux_playback_id;

    if (!assetId || !playbackId) {
      throw new HttpError(404, { message: 'Video not found or missing mux ids' });
    }

    // 2) Mux: retrieve asset tracks
    const assetJson = await muxGetAsset(assetId);
    const tracks = assetJson?.data?.tracks || [];

    // 3) Nađi EN track
    const enTrack = pickTextTrackByLang(tracks, 'en');
    if (!enTrack?.id) {
      throw new HttpError(404, {
        message: 'English subtitle track (en) does not exist on this asset',
      });
    }

    // 4) Skini EN VTT
    const { vttText: enVtt } = await fetchVttFromMux(playbackId, enTrack.id);
    if (!enVtt || !enVtt.trim()) {
      throw new HttpError(502, { message: 'Mux returned empty VTT' });
    }

    // 5) Pošalji na n8n i prosledi samo "result"
    const webhookUrl = process.env.N8N_GENERATE_DETAILS_WEBHOOK; // promeni ako ti je drugačije
    const token = process.env.N8N_TRANSLATE_SUBS_BEARER_TOKEN;

    if (!webhookUrl) throw new HttpError(500, { message: 'N8N webhook not configured' });
    if (!token) throw new HttpError(500, { message: 'N8N bearer token missing' });

    const r = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `${token}`,
      },
      body: JSON.stringify({ type, vttText: enVtt }),
    });

    if (!r.ok) {
      const txt = await r.text().catch(() => '');
      throw new HttpError(502, {
        message: 'n8n error',
        details: `N8N_BAD_STATUS:${r.status}${txt ? `:${txt.slice(0, 500)}` : ''}`,
      });
    }

    const data = await r.json().catch(() => null);
    if (!data || typeof data !== 'object' || !('result' in data)) {
      throw new HttpError(502, { message: 'n8n returned invalid response', details: data });
    }

    return data;
  } catch (err) {
    if (err instanceof HttpError) throw err;
    console.error('autogenerate subtitles error:', err);

    const msg = String(err?.message || '');
    if (msg.startsWith('MUX_')) {
      throw new HttpError(502, { message: 'Mux error', details: msg });
    }

    throw new HttpError(500, { message: 'Server error' });
  }
}
