import express from 'express';
import { requireAuth } from '../../middleware/auth.js';
import { requirePermission } from '../authorization/authorization.middleware.js';
import { Permissions } from '../authorization/permission.constants.js';
import { requireVideoAccess } from '../authorization/resource-authorization.js';
import {
  handleGetSubtitle,
  handleReplaceSubtitle,
  handleReplaceSubtitleV2,
  handleDeleteSubtitle,
  handleAutogenerateAndReplaceSubtitle,
  handleAutogenerateSubtitlePreview,
  handleAutogenerateDetails,
  handlePatchVideoDetails,
  handleGetMyVideos,
  handleDeleteVideo,
  handleVideoThumbnailUpload,
} from './video-moderation.controller.js';
import { subtitleUploadMiddleware, videoThumbnailUploadMiddleware } from './video.middleware.js';

const router = express.Router();

const requireVideoUpdate = requireVideoAccess({
  ownPermission: Permissions.VIDEOS_UPDATE_OWN,
  anyPermission: Permissions.VIDEOS_UPDATE_ANY,
});
const requireVideoDelete = requireVideoAccess({
  ownPermission: Permissions.VIDEOS_DELETE_OWN,
  anyPermission: Permissions.VIDEOS_DELETE_ANY,
});

router.get('/subtitle/:videoId', requireAuth, requireVideoUpdate, handleGetSubtitle);
router.post(
  '/subtitle/replace/:videoId',
  requireAuth,
  requireVideoUpdate,
  subtitleUploadMiddleware,
  handleReplaceSubtitle,
);
router.post(
  '/subtitle/replacev2/:videoId',
  requireAuth,
  requireVideoUpdate,
  express.json({ limit: '2mb' }),
  handleReplaceSubtitleV2,
);
router.delete('/subtitle/:videoId', requireAuth, requireVideoUpdate, handleDeleteSubtitle);
router.post(
  '/subtitle/autogenerate/:videoId',
  requireAuth,
  requireVideoUpdate,
  handleAutogenerateAndReplaceSubtitle,
);
router.get(
  '/subtitle/autogenerate/:videoId',
  requireAuth,
  requireVideoUpdate,
  handleAutogenerateSubtitlePreview,
);
router.get(
  '/details/autogenerate/:videoId',
  requireAuth,
  requireVideoUpdate,
  handleAutogenerateDetails,
);

router.patch('/video-details/:videoId', requireAuth, requireVideoUpdate, handlePatchVideoDetails);
router.post(
  '/:videoId/thumbnail',
  requireAuth,
  requireVideoUpdate,
  videoThumbnailUploadMiddleware,
  handleVideoThumbnailUpload,
);

router.get(
  '/my/videos',
  requireAuth,
  requirePermission(Permissions.VIDEOS_UPDATE_OWN),
  handleGetMyVideos,
);
router.delete('/video/:videoId', requireAuth, requireVideoDelete, handleDeleteVideo);

export default router;
