import express from 'express';
import { requireAuth, requireAdmin } from '../../middleware/auth.js';
import {
  subtitleUploadMiddleware,
  handleGetSubtitle,
  handleReplaceSubtitle,
  handleReplaceSubtitleV2,
  handleDeleteSubtitle,
  handleAutogenerateAndReplaceSubtitle,
  handleAutogenerateSubtitlePreview,
  handleAutogenerateDetails,
  handlePatchVideoDetails,
  handleGetMyVideos,
  handleDeleteVideo,
} from './video-moderation.service.js';

const router = express.Router();

router.get('/subtitle/:videoId', requireAuth, requireAdmin, handleGetSubtitle);
router.post('/subtitle/replace/:videoId', requireAuth, requireAdmin, subtitleUploadMiddleware, handleReplaceSubtitle);
router.post('/subtitle/replacev2/:videoId', requireAuth, requireAdmin, express.json({ limit: '2mb' }), handleReplaceSubtitleV2);
router.delete('/subtitle/:videoId', requireAuth, requireAdmin, handleDeleteSubtitle);
router.post('/subtitle/autogenerate/:videoId', requireAuth, requireAdmin, handleAutogenerateAndReplaceSubtitle);
router.get('/subtitle/autogenerate/:videoId', requireAuth, requireAdmin, handleAutogenerateSubtitlePreview);
router.get('/details/autogenerate/:videoId', requireAuth, requireAdmin, handleAutogenerateDetails);
router.patch('/video-details/:videoId', requireAuth, requireAdmin, handlePatchVideoDetails);
router.get('/my/videos', requireAuth, handleGetMyVideos);
router.delete('/video/:videoId', requireAuth, requireAdmin, handleDeleteVideo);

export default router;
